// glossaryファイル Memo
`use strict`
const glossary = [
{target:`Devs環境`, content:`開発環境。<br>【Dev】`},
{target:`Stage環境`, content:`試作環境（ユーザーテスト）。<br>【Dev】`},
{target:`Prod環境`, content:`ユーザー環境。<br>【Dev】`},
{target:`Sync（Synchronization）`, content:`同期。情報共有。<br>【Dev】`},
{target:`Synt（Synthesize）`, content:`合成する。総合する。<br>【Dev】`},
{target:`chore`, content:`雑務。<br>【Dev】`},
{target:`イテレーション`, content:`「要件定義→設計→実装→テスト」を機能単位で進める短期間（1週間～4週間ほど）の開発サイクル。<br>【Dev】`},
{target:`ストーリーポイント`, content:`システムが提供する価値実装に必要な作業コストの見積り単位。<br>【Dev】`},
{target:`ベロシティ`, content:`ストーリーポイントを開発チームでどのような計画で消化していくかを表す指標。<br>【Dev】`},
{target:`Feature flag`, content:`プロダクト開発時に新機能の公開（リリース）や変更を簡単に制御できるようにする仕組み。<br>【Dev】`},
{target:`チャッピー（Chappie）`, content:`大規模言語モデルGPTのAPIサービスを活用したツール。<br>【Dev】`},
{target:`metrics`, content:`測定基準、尺度。<br>【Dev】`},
{target:`Engagement`, content:`開発期間。<br>【Dev】`},
{target:`ステータスコード`, content:`HTTPプロトコルでクライアントとサーバーの間でやり取りされるリクエストおよびレスポンスの状態を示す3桁の数値。<br>クライアントがリクエストを正常に処理したか、エラーが発生したか、またはリダイレクトが行われたかなどの状態を示す。<br>代表的なステータスコード<br>200：OK、リクエストが成功し、レスポンスが正常に返された<br>201：Created、リクエストが成功し、新しいリソースが作成された<br>204：No Content、リクエストが成功し、レスポンスにはコンテンツが含まれていない<br>400：Bad Request、クライアントのリクエストが不正であるため、サーバーが理解できない<br>401：Unauthorized、認証が必要なリソースに対するリクエストが認証されていない<br>403：Forbidden、クライアントがリソースにアクセスする権限がない<br>404：Not Found、リクエストされたリソースが見つからない<br>500：Internal Server Error、サーバーで予期しないエラーが発生<br>【Dev】`},
{target:`text`, content:`テキスト情報を表示するコンポーネント。<br>【UI】`},
{target:`button`, content:`クリックで操作を実行するコンポーネント。<br>【UI】`},
{target:`input field`, content:`ユーザーが入力する領域のコンポーネント。<br>【UI】`},
{target:`placeholder text`, content:`入力例を示す薄い文字。<br>【UI】`},
{target:`drop list`, content:`選択肢を表示するリストのコンポーネント。<br>【UI】`},
{target:`checkbox`, content:`複数選択可能なボックスのコンポーネント。<br>【UI】`},
{target:`pull-down button`, content:`複数の選択肢の中から1つだけ選択できるコンポーネント。<br>【UI】`},
{target:`buck button`, content:`戻る操作をするボタンのコンポーネント。<br>【UI】`},
{target:`time`, content:`時間を表示するコンポーネント。<br>【UI】`},
{target:`number`, content:`数値を表示するコンポーネント。<br>【UI】`},
{target:`hyperlink text`, content:`リンクテキストのコンポーネント。<br>【UI】`},
{target:`hyperlink URL display field`, content:`リンク先URLを表示する領域のコンポーネント。<br>【UI】`},
{target:`radio button`, content:`複数の選択肢から一つだけ選択できるコンポーネント。<br>【UI】`},
{target:`segmented controller`, content:`情報を切り分けて表示するコンポーネント。<br>【UI】`},
{target:`hamburger navigation`, content:`ナビゲーションバーの省略表示するコンポーネント。<br>【UI】`},
{target:`header`, content:`ページやアプリのタイトル部分。<br>【UI】`},
{target:`tab`, content:`並列な情報を複数画面に分けて表示する際に使用するコンポーネント。<br>【UI】`},
{target:`navigation bar`, content:`ユーザーが目的地へ最短でアクセスするためのコンポーネント。<br>【UI】`},
{target:`accordion`, content:`クリックすることで開閉するコンポーネント。<br>【UI】`},
{target:`list`, content:`行の表現に使用するコンポーネント。<br>【UI】`},
{target:`card`, content:`対象ごとに情報をまとめるような場合に利用するコンポーネント。<br>【UI】`},
{target:`table`, content:`表形式で表示するコンポーネント。<br>【UI】`},
{target:`alert`, content:`ユーザーの注意を惹くメッセージを表示するコンポーネント。<br>【UI】`},
{target:`progress bar`, content:`操作の進捗状況や処理状況を棒状の領域内の色の範囲の変化で表現するコンポーネント。<br>【UI】`},
{target:`spinner`, content:`プログレスバーのバー部分が円状になっているコンポーネント。<br>【UI】`},
{target:`tooltip`, content:`用語やコンポーネントなどにマウスオーバーした際に補足情報を表示するコンポーネント。<br>【UI】`},
{target:`タイポグラフィ`, content:`文字や文章を視覚的に整理し、美しく表現する技術。<br>【UI】`},
{target:`非活性`, content:`コンポーネントが操作できない状態。<br>【UI】`},
{target:`当たり判定`, content:`クリック可能領域の判定。<br>【UI】`},
{target:`モーダル（Modal）`, content:`画面に突然現れるウィンドウ。<br>「入力モード」や「編集モード」など特定の「モードがある状態」を指す。<br>【UI】`},
{target:`モーダルウィンドウ`, content:`ユーザーに重要な情報やエラーメッセージを伝えるために表示される、Webサイトやアプリの画面に表示される別のウィンドウ。<br>【UI】`},
{target:`ポップアップ（Popup）`, content:`何かが飛び出したり現れたりする様子。<br>操作を妨げない補足的な情報提供。<br>【UI】`},
{target:`ポップアップウィンドウ`, content:`画面に突然現れるウィンドウ。<br>【UI】`},
{target:`ファビコン（Favorite Iconの略）`, content:`ウェブサイトのシンボルとして用いられる小さな画像。<br>【UI】`},
{target:`ダイアログ`, content:`システムとユーザー間のインタラクションを意図したもの。<br>【UI】`},
{target:`Tailwind CSS`, content:`ウェブサイトやWebアプリケーションのスタイリングを効率的に行うためのCSSフレームワーク。<br>ウェブページの構築やデザインにおいて、マークアップの中に直接、定義済みのクラスの形でHTML内にCSSを記述できる。<br>【DevInfo】`},
{target:`Amazon S3（Amazon Simple Storage Service）`, content:`オブジェクトストレージサービス。<br>スケーラビリティ、データ可用性、セキュリティ、パフォーマンスを提供する。セキュリティ、データ保護、コンプライアンス、およびアクセスコントロール機能でデータを保護する。セキュア、プライベート、かつデフォルトで暗号化されており、リソースへのアクセスリクエストを監視するために多数の監査機能もサポートする。<br>【DevInfo】`},
{target:`TORO（TOyota Reliable Observatory/Orchestration）`, content:`クラウドインフラとアプリケーションインフラ。<br>AWSとTerraformをベースに、AWS OrganizationsやControl Towerなどを用いて、ユーザーが申請してから約2営業日で基礎的なセキュリティ設定が完了しているクラウド環境が提供できる。<br>【DevInfo】`},
{target:`Cognito`, content:`アプリケーションの認証認可を行うサービス。<br>アカウント管理・認証認可の付与をAWS側で行ってくれる、フルマネージドサービス。<br>【DevInfo】`},
{target:`AWS VPN Client`, content:`クライアントベースのマネージドVPNサービス。<br>リモート端末からAWSへのセキュアなプライベート通信を確立。VPNを実装するためのソフトウェアとしてOpenVPNを利用。そのため、実装にあたってはクライアント端末にもOpenVPNベースのVPNソフトウェアを導入する必要がある<br>【DevInfo】`},
{target:`CMS（Contents Management System）`, content:`Webサイトのコンテンツを管理するシステム。<br>【DevInfo】`},
{target:`ラズパイ（Raspberry Piの略）`, content:`IoT開発を手軽に体験できるツール。<br>カードサイズでありながら、高い可能性を秘めたコンピューター。<br>【DevInfo】`},
{target:`OKR`, content:`目標と主要な結果の略で、目標管理の手法のひとつ。<br>企業や組織の目標と従業員の目標をリンクさせ、組織全体の方向性を明確にすることを目的とする。<br>【DevInfo】`},
{target:`GA（Google analysis）`, content:`Googleが提供するWebサイトのアクセス解析ツール。<br>ウェブサイトのアクセス状況を分析し、より良いウェブサイト運営に役立つ情報を得るために使わる。<br>【DevInfo】`},
{target:`CCoE（Cloud Center of Excellence）`, content:`企業や組織内でクラウドコンピューティング技術の採用、運用、および最適化を推進するための専門チームまたは機能ユニット。<br>【DevInfo】`},
{target:`XVL（eXtensible Virtual world description Language）`, content:`軽量3次元フォーマット。<br>ラティス・テクノロジー株式会社が開発した、世界最高水準の基本性能を実現した軽量3次元フォーマット。CAD画像を軽量で表示。<br>【Info】`},
{target:`スクラッチ開発`, content:`ソフトウェアやコンピュータシステムをゼロの状態から作り出す開発手法。<br>【Info】`},
{target:`Build-Measure-Learn`, content:`リーンスタートアップの中心的な考え方。<br>この考えを何回も回していくことが大切。<br>&emsp;IDEAS：構想を形にする<br>&emsp;BUILD：MVPを実験的に試す<br>&emsp;PRODUCT：実際のデータを収集する<br>&emsp;MEASURE：反応や使用状況を測定する<br>&emsp;DATA：結果を元に分析を行う<br>&emsp;LEARN：仮説が正しかったか評価し学習する<br>【Info】`},
{target:`Product Driven開発（PLG）`, content:`製品主導型開発。<br>顧客のニーズやビジネスの目標を踏まえ、顧客に価値を提供するプロダクトを開発・提供。<br>【Info】`},
{target:`データドリブン開発`, content:`データ分析に基づいて製品ライフサイクル全体を通して意思決定を導く。<br>【Info】`},
{target:`プロダクトライン開発`, content:`類似する製品群（プロダクトライン）を開発するための共有資産を定義し、その共有資産を有効活用する。<br>【Info】`},
{target:`モデルドリブン`, content:`モデル図をもとにプログラムを自動生成することで、エンジニアの手作業をサポート。<br>【Info】`},
{target:`ACoE`, content:`Arce Pivots組織。<br>【Info】`},
{target:`正味作業`, content:`作業を順序どおりに行った1サイクルの最小時間。<br>実質的な作業のみにかかる時間。<br>【現場】`},
{target:`付随作業`, content:`本来の業務に付随して行われる業務。<br>【現場】`},
{target:`TIS`, content:`組付指示書、組立指示図の略称。<br>【現場】`},
{target:`＿A`, content:`車両工場での組付工程の略称。<br>【現場】`},
{target:`＿B`, content:`ボディの略称。<br>【現場】`},
{target:`＿C`, content:`鋳造の略称。<br>【現場】`},
{target:`＿E`, content:`電子組付けの略称。<br>【現場】`},
{target:`＿F`, content:`鍛造の略称。<br>【現場】`},
{target:`＿G`, content:`外注の略称。<br>【現場】`},
{target:`＿H`, content:`熱処理の略称。<br>【現場】`},
{target:`＿K`, content:`組付けの略称。<br>【現場】`},
{target:`＿M`, content:`機械加工の略称。<br>【現場】`},
{target:`＿P`, content:`プレスの略称。<br>【現場】`},
{target:`＿R`, content:`樹脂部品などの成型の略称。<br>【現場】`},
{target:`＿T`, content:`塗装の略称。<br>【現場】`},
{target:`＿W`, content:`溶接の略称。<br>【現場】`},
{target:`＿モ`, content:`モデルチェンジの略称。<br>【現場】`},
{target:`＿カ`, content:`車型追加の略称。<br>【現場】`},
{target:`＿マ`, content:`マイナーチェンジの略称。<br>【現場】`},
{target:`MG`, content:`モータとジェネレータ。<br>【現場】`},
]
